[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 9

[font.normal]
family = "VictorMono Nerd Font"
style = "Regular"

[font.bold]
family = "VictorMono Nerd Font"
style = "Bold"

[font.italic]
family = "VictorMono Nerd Font"
style = "Italic"

[window]
opacity = 0.9
dynamic_padding = true

[window.padding]
x = 4
y = 4

[mouse]
hide_when_typing = true
